name: Build OpenWrt 24.10.4 for ZBT-Z8102AX-eMMC

on:
  workflow_dispatch:
    inputs:
      clean_build:
        description: '清除构建缓存'
        required: false
        default: 'false'
      skip_download:
        description: '跳过下载阶段'
        required: false
        default: 'false'

env:
  OPENWRT_VERSION: "24.10.4"
  OPENWRT_BRANCH: "openwrt-24.10"
  TARGET: "mediatek"
  SUBTARGET: "filogic"
  DEVICE: "zbtlink_z8102ax-emmc"

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    
    steps:
    # 第一步：检出仓库到自定义目录
    - name: 检出仓库内容
      uses: actions/checkout@v4
      with:
        path: custom-src
        fetch-depth: 0

    # 第二步：设置编译环境
    - name: 设置构建环境
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential ccache ecj fastjar file g++ gawk gettext git \
          libelf-dev libncurses5-dev libncursesw5-dev libssl-dev \
          python3 python3-setuptools python3-dev rsync unzip wget \
          xsltproc zlib1g-dev cmake pkg-config flex bison

        sudo mkdir -p /opt/ccache
        sudo chmod 777 /opt/ccache
        echo "CCACHE_DIR=/opt/ccache" >> $GITHUB_ENV
        echo "/usr/lib/ccache" >> $GITHUB_PATH
        ccache -M 10G

    # 第三步：显示目录结构以便调试
    - name: 分析目录结构
      run: |
        echo "=== 目录结构分析 ==="
        echo "当前工作目录: $(pwd)"
        echo ""
        echo "custom-src 目录内容:"
        ls -la custom-src/
        echo ""
        echo "查找配置文件:"
        find custom-src -type f \( -name "*.dts" -o -name "*.mk" -o -name "*.config" \) 2>/dev/null

    # 第四步：克隆OpenWrt源码
    - name: 克隆 OpenWrt 源码
      run: |
        echo "正在克隆 OpenWrt ${{ env.OPENWRT_BRANCH }} 分支..."
        
        git clone https://git.openwrt.org/openwrt/openwrt.git \
          --branch ${{ env.OPENWRT_BRANCH }} \
          --single-branch \
          --depth=1 \
          openwrt-build

        cd openwrt-build
        git submodule update --init --recursive

    # 第五步：应用自定义配置文件
    - name: 应用自定义配置
      run: |
        cd openwrt-build
        
        echo "=== 应用自定义配置文件 ==="
        
        # 1. 查找并复制DTS文件
        echo "1. 查找DTS文件..."
        DTS_FILE=$(find ../custom-src -name "mt7981b-zbt-z8102ax-emmc.dts" -type f | head -1)
        
        if [ -f "$DTS_FILE" ]; then
          echo "找到DTS文件: $DTS_FILE"
          mkdir -p target/linux/${{ env.TARGET }}/dts/
          cp "$DTS_FILE" target/linux/${{ env.TARGET }}/dts/
          echo "✅ DTS文件已复制到: target/linux/${{ env.TARGET }}/dts/mt7981b-zbt-z8102ax-emmc.dts"
        else
          echo "❌ 错误：未找到DTS文件"
          find ../custom-src -type f -name "*.dts" 2>/dev/null
          exit 1
        fi
        
        # 2. 查找并复制.mk文件（设备定义）
        echo ""
        echo "2. 查找.mk文件..."
        MK_FILE=$(find ../custom-src -name "filogic.mk" -o -name "*.mk" | grep -i "mediatek" | head -1)
        
        if [ -f "$MK_FILE" ]; then
          echo "找到.mk文件: $MK_FILE"
          mkdir -p target/linux/${{ env.TARGET }}/image/
          cp "$MK_FILE" target/linux/${{ env.TARGET }}/image/
          echo "✅ .mk文件已复制"
        else
          echo "⚠️ 警告：未找到.mk文件，使用OpenWrt默认配置"
        fi
        
        # 3. 复制config配置文件到构建目录
        echo ""
        echo "3. 查找config配置文件..."
        CONFIG_FILE=$(find ../custom-src -name "zbtlink_z8102ax-emmc.config" -type f | head -1)
        
        if [ -f "$CONFIG_FILE" ]; then
          echo "找到config文件: $CONFIG_FILE"
          # 复制到构建目录以便后续使用
          cp "$CONFIG_FILE" device-config.config
          echo "✅ config文件已复制为: device-config.config"
          echo "文件内容预览（前20行）:"
          head -20 device-config.config
        else
          echo "❌ 错误：未找到config配置文件: zbtlink_z8102ax-emmc.config"
          find ../custom-src -name "*.config" -type f 2>/dev/null
          exit 1
        fi

    # 第六步：更新和安装软件源
    - name: 更新和安装软件源
      run: |
        cd openwrt-build
        
        echo "更新软件源..."
        ./scripts/feeds update -a
        
        echo "安装软件包..."
        ./scripts/feeds install -a

    # 第七步：配置OpenWrt
    - name: 配置 OpenWrt
      run: |
        cd openwrt-build
        
        # 清理选项
        if [[ "${{ github.event.inputs.clean_build }}" == "true" ]]; then
          echo "执行清理..."
          make clean
        fi
        
        # 生成默认配置
        make defconfig
        
        # 应用基础配置（确保目标平台正确）
        echo "CONFIG_TARGET_mediatek=y" >> .config
        echo "CONFIG_TARGET_mediatek_filogic=y" >> .config
        echo "CONFIG_TARGET_mediatek_filogic_DEVICE_zbtlink_z8102ax-emmc=y" >> .config
        
        # 应用自定义配置文件（如果有）
        if [ -f "device-config.config" ]; then
          echo "应用自定义配置文件..."
          cat device-config.config >> .config
          echo "✅ 自定义配置文件已应用"
        else
          echo "⚠️ 警告：未找到自定义配置文件，使用基础配置"
          # 添加一些基础包作为后备
          echo "CONFIG_PACKAGE_kmod-mmc=y" >> .config
          echo "CONFIG_PACKAGE_kmod-sdhci-mtk=y" >> .config
          echo "CONFIG_PACKAGE_block-mount=y" >> .config
        fi
        
        # 最终验证配置
        make defconfig
        
        echo "=== 配置摘要 ==="
        echo "目标平台:"
        grep "CONFIG_TARGET" .config | head -5
        echo ""
        echo "设备相关配置:"
        grep -i "zbtlink\|z8102ax\|filogic" .config || echo "未找到特定设备配置"
        echo ""
        echo "总配置项数: $(wc -l < .config)"

    # 第八步：下载软件包源码
    - name: 下载软件包源码
      if: github.event.inputs.skip_download != 'true'
      run: |
        cd openwrt-build
        echo "下载软件包源码..."
        make download -j$(nproc) || make download -j1

    # 第九步：编译OpenWrt
    - name: 编译 OpenWrt
      run: |
        cd openwrt-build
        
        echo "开始编译 OpenWrt ${{ env.OPENWRT_VERSION }}..."
        echo "目标设备: ${{ env.DEVICE }}"
        echo "使用的配置文件:"
        ls -la device-config.config 2>/dev/null || echo "未使用自定义配置文件"
        
        START_TIME=$(date +%s)
        
        # 编译（首次建议单线程，便于调试）
        echo "开始编译过程..."
        time make -j1 V=s 2>&1 | tee build.log
        
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        
        echo "编译耗时: $((DURATION / 60))分$((DURATION % 60))秒"
        
        # 验证构建结果
        FIRMWARE_DIR="bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}"
        
        if [ -d "$FIRMWARE_DIR" ]; then
          BIN_FILES=$(find $FIRMWARE_DIR -name "*.bin" -type f)
          BIN_COUNT=$(echo "$BIN_FILES" | wc -l)
          
          if [ "$BIN_COUNT" -gt 0 ]; then
            echo "✅ 编译成功！生成 $BIN_COUNT 个固件文件"
            echo "$BIN_FILES" | head -5 | while read f; do
              echo "  - $(basename $f) ($(ls -lh "$f" | awk '{print $5}'))"
            done
            
            # 检查是否包含sysupgrade文件
            SYSUPGRADE=$(find $FIRMWARE_DIR -name "*sysupgrade*" -type f | head -1)
            if [ -n "$SYSUPGRADE" ]; then
              echo "✅ 包含sysupgrade文件: $(basename $SYSUPGRADE)"
            fi
          else
            echo "❌ 编译完成但未生成固件文件"
            echo "请检查 build.log 文件中的错误信息"
            exit 1
          fi
        else
          echo "❌ 产出目录不存在: $FIRMWARE_DIR"
          exit 1
        fi

    # 第十步：上传产物
    - name: 上传固件产物
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-${{ env.OPENWRT_VERSION }}-${{ env.DEVICE }}
        path: |
          openwrt-build/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/*.bin
          openwrt-build/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/sha256sums
          openwrt-build/device-config.config
        if-no-files-found: error
        retention-days: 90

    - name: 上传编译日志
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-${{ env.OPENWRT_VERSION }}-logs
        path: |
          openwrt-build/build.log
          openwrt-build/.config
        if-no-files-found: warn
        retention-days: 30
